language: php

services:
  - mysql
  - redis-server

php:
  - 7.2
  
before_script:
  - nvm install lts/dubnium 
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE portail;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:fresh --seed
  - npm -g i npm
  - npm i
  - npm run prod
  - php artisan portail:clear

script:
  - php artisan portail:test
